# Example Travis config. See the entire example: https://github.com/JonathanPorta/ci-build

language: objective-c
osx_image: xcode61
rvm:
- 2.1.2
sudo: true
before_install:
- chmod a+x ./Scripts/install.sh
install:
- ./Scripts/install.sh
before_script:
- chmod a+x ./Scripts/build.sh
script:
- ./Scripts/build.sh